- hosts: localhost
  gather_facts: False
  vars_files:
    - variables.yaml
  tasks:
    - name: create key pair using key_material obtained using 'file' lookup plugin  
      amazon.aws.ec2_key:
        name: my-local-key
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: eu-north-1
        key_material: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Access AWS using an iam user credentials
      amazon.aws.ec2_instance:
        name: cloud-container
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "my-local-key"
        instance_type: t3.micro
        security_group: launch-wizard-2
        image_id: ami-0914547665e6a707c
        region: eu-north-1
