services:
  webserver:
    image: iamfrancesjoffany/upskill-devops:webserver
    container_name: webserver
    volumes: 
      - restaurant-data:/var/www/restaurant-css-framework
    ports:
      - "80:80"
    networks:
      - restaurant 
    depends_on:
      - php-fpm
      - mysql
  
  php-fpm:
  image: iamfrancesjoffany/upskill-devops:php-fpm
    container_name: php-fpm
    environment:
      - mysql-server-name=mysql
      - mysql-server-passwd=root
    volumes:
      - restaurant-data:/var/www/restaurant-css-framework:ro
    networks:
      - restaurant
    depends_on:
      - mysql

  mysql:
    image: iamfrancesjoffany/upskill-devops:mysql
    container_name: mysql 
    ports: 
      - "3306:3306" 
    networks:
      - restaurant

volumes:
    restaurant-data: 

networks:
    restaurant:
      name: restaurant-network
