- name: Create new instance and add new instance's public IP address
  hosts: local
  connection: local
  gather_facts: False
  vars_files:
    - variables.yaml
  tasks:
    - name: create key pair using key_material obtained using 'file' lookup plugin  
      amazon.aws.ec2_key:
       name: my-github-key
       aws_access_key: "{{ aws_access_key }}"
       aws_secret_key: "{{ aws_secret_key }}"
       region: eu-north-1
       key_material: "{{ lookup('file', '~/.ssh/id_rsa_github.pub') }}"

    - name: Access AWS using an iam user credentials
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "my-github-key"
        instance_type: t3.micro
        security_group: launch-wizard-2
        image_id: ami-0914547665e6a707c
        region: eu-north-1
        wait: true
        wait_timeout: 1000
      register: ec2

        #   - name: Start a particular instance by its ID
        #      amazon.aws.ec2_instance:
        #        state: started
        #        instance_ids:
        #          - "{{ ec2.instances[0].instance_id }}"
        #        region: eu-north-1
        #        aws_access_key: "{{ aws_access_key }}"
        #        aws_secret_key: "{{ aws_secret_key }}"
        #        wait: true
        #wait_timeout: 1000
        #      register: ec2
    
    - debug:
        msg: "{{ ec2.instances[0].network_interfaces[0].association.public_ip }}"
    
    - name: Add new host to group 'aws_host'
      ansible.builtin.add_host:
        name: "{{ ec2.instances[0].network_interfaces[0].association.public_ip }}"
        groups: aws_host
