- name: Automate deployment for Restaurant website
  hosts: aws_host
  become: true
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: Update packages
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - python3-pip
        - gnupg
        - software-properties-common
        

    - name: Create directory for Docker's GPG key
      file: 
        path: /etc/apt/keyrings
        state: directory
        mode: '0755' 

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Print architecture variables
      ansible.builtin.debug:
        msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - containerd.io

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: 
          - docker
          #- docker==6.1.3
          - docker-compose

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker
        - containerd
    - ansible.builtin.debug: 
        var: status
    
    - name: Log into DockerHub
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_token }}"
        #api_version: "1.25"
      register: login_results
    - ansible.builtin.debug: 
        var: login_results

    # This task pull multiple images that was indicated in loop
    - name: Pull Docker Images
      community.general.docker_image:
        name:  "{{ item }}"
        source: pull 
      loop:
        - iamfrancesjoffany/upskill-devops:webserver
        - iamfrancesjoffany/upskill-devops:php-fpm
        - iamfrancesjoffany/upskill-devops:mysql
    
    - name: Create and start services
      community.docker.docker_compose:
        project_name: serve_restaurant
        definition:
          services:
            webserver:
              image: iamfrancesjoffany/upskill-devops:webserver
              container_name: webserver
              volumes:
                - restaurant-data:/var/www/restaurant-css-framework
              ports:
                - "80:80"
              networks:
                - restaurant
              depends_on:
                - php-fpm
                - mysql

            php-fpm:
              image: iamfrancesjoffany/upskill-devops:php-fpm
              container_name: php-fpm
              environment:
                - mysql-server-name=mysql
                - mysql-server-passwd=root
              volumes:
                - restaurant-data:/var/www/restaurant-css-framework:ro
              networks:
                - restaurant
              depends_on:
                - mysql

            mysql:
              image: iamfrancesjoffany/upskill-devops:mysql
              container_name: mysql
              ports:
                - "3306:3306"
              networks:
                - restaurant

          volumes:
              restaurant-data:

          networks:
              restaurant:
                name: restaurant-network

      register: output      
