- name: Create new instance and add new instance's public IP address
  hosts: local
  connection: local
  become: true
  gather_facts: false
  vars_files:
    - variables.yaml
  
  tasks:
    - name: Install packages
      ansible.builtin.pip:
        name: 
          - botocore
          - boto3
          - petname
          
    # Start testing for ansible_python_interpreter
    - command: "{{ ansible_python_interpreter | default('/usr/bin/python') }} -c 'import {{ module }}; print({{ module }})'"
      vars:
        module: petname
      register: test

    - debug:
        var: test.stdout
    # End testing for ansible_python_interpreter

    - name: create key pair using key_material obtained using 'file' lookup plugin
      amazon.aws.ec2_key:
        name: my-github-key
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: us-east-1
        key_material: "ssh-rsa {{ ssh_public_key }}" #{{ lookup('file', '~/.ssh/id_rsa_github.pub') }}
      no_log: true
      
    - name: Access AWS using an iam user credentials
      amazon.aws.ec2_instance:
        name: "{{ lookup('community.general.random_pet') }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: "my-github-key"
        instance_type: t2.micro
        security_group: launch-wizard-1
        image_id: ami-04b4f1a9cf54c11d0
        region: us-east-1
        network:
          assign_public_ip: true
      register: ec2

    #- debug:
    #    msg: "{{ec2}}" 

    - name: Add new host to group 'aws_host'
      ansible.builtin.add_host:
        name: "{{ ec2.instances[0].public_dns_name }}"
        groups: aws_host

- name: Automate deployment for Restaurant website
  hosts: aws_host
  become: true
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64

  tasks:
    - name: Update packages
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - python3-pip
        - gnupg
        - software-properties-common
        - python3-venv

    - name: Create directory for Docker's GPG key
      ansible.builtin.file: 
        path: /etc/apt/keyrings
        state: directory
        mode: '0755' 

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Print architecture variables
      ansible.builtin.debug:
        msg: "Architecture: {{ ansible_architecture }}, Codename: {{ ansible_lsb.codename }}"

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: >-
          deb [arch={{ arch_mapping[ansible_architecture] | default(ansible_architecture) }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        filename: docker
        state: present

    - name: Install Docker and related packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - docker-ce
        - containerd.io

    - name: Create File for virtualenv
      ansible.builtin.file:
        path: my-app
        state: directory

    #- name: Create virtual environment
    #  ansible.builtin.command: python3 -m venv my-env
    #  args:
    #    chdir: my-app/
    
    #- name: Check the current directory
    #  ansible.builtin.shell:
    #    cmd: pwd

    #- name: Activate virtual environment
    #  ansible.builtin.command: source my-env/bin/activate
    #  args:
    #    chdir: my-app/
        
    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: 
          #- docker
          - docker==6.1.3
          - docker-compose
          # downgrade requests
          - requests==2.31.0
        #chdir: cd -
        virtualenv: my_app/my-env
        virtualenv_command: python3 -m venv my-env
        virtualenv_site_packages: true


    - name: Just get the list from default pip
      community.general.pip_package_info:

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker
        - containerd
    - ansible.builtin.debug: 
        var: status
    
    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_token }}"
        api_version: "1.44"
      register: login_results
    - ansible.builtin.debug: 
        var: login_results

    # This task pull multiple images that was indicated in loop
    - name: Pull Docker Images
      community.general.docker_image:
        name:  "{{ item }}"
        source: pull 
      loop:
        - iamfrancesjoffany/upskill-devops:webserver
        - iamfrancesjoffany/upskill-devops:php-fpm
        - iamfrancesjoffany/upskill-devops:mysql
    
    - name: Create and start services
      community.docker.docker_compose_v2:
        project_name: serve_restaurant
        definition:
          services:
            webserver:
              image: iamfrancesjoffany/upskill-devops:webserver
              container_name: webserver
              volumes:
                - restaurant-data:/var/www/restaurant-css-framework
              ports:
                - "80:80"
              networks:
                - restaurant
              depends_on:
                - php-fpm
                - mysql

            php-fpm:
              image: iamfrancesjoffany/upskill-devops:php-fpm
              container_name: php-fpm
              environment:
                - mysql-server-name=mysql
                - mysql-server-passwd=root
              volumes:
                - restaurant-data:/var/www/restaurant-css-framework:ro
              networks:
                - restaurant
              depends_on:
                - mysql

            mysql:
              image: iamfrancesjoffany/upskill-devops:mysql
              container_name: mysql
              ports:
                - "3306:3306"
              networks:
                - restaurant

          volumes:
              restaurant-data:

          networks:
              restaurant:
                name: restaurant-network

      register: output      